version: "3"
services:
  postgres-tictactoe:
    container_name: postgres-tictactoe
    image: postgres:latest
    ports:
      - "9874:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin-tictactoe:
    links:
      - postgres-tictactoe:postgres-tictactoe
    container_name: pgadmin-tictactoe
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
